language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
# Fetch dependencies
install:
    - pip install -vr requirements.txt
# Run supybot-test
script:
  - cd .. && supybot-test -c supybot-lastfm
notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - python: "3.2"
        - python: "3.3"
        - python: "pypy"
        - python: "pypy3"
